# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.35.1
# 

Name:       harbour-deadascend

# >> macros
# << macros
%define assets_version 1.1.3
%define assets_pkgname %{name}-assets

Summary:    A horde of zombies have chased you to the old radio tower
Version:    1.1.3
Release:    0
Group:      Applications
License:    MIT
URL:        https://blackgrain.dk/games/deadascend/
Source0:    %{name}-%{version}.tar.gz
Source100:  harbour-deadascend.yaml
Source101:  harbour-deadascend-rpmlintrc
Patch0:     qak-qt5.6.patch
Requires:   %{assets_pkgname} = %{assets_version}
BuildRequires:  pkgconfig(sailfishapp)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Multimedia)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  qt5-qttools-linguist
BuildRequires:  qt5-qmake
BuildRequires:  sailfish-svg2png
BuildRequires:  qml-rpm-macros
BuildRequires:  desktop-file-utils

%description
A hand-drawn, open source, point'n'click-like 2D adventure game.

A horde of Zombies chased you to the old radio tower. Your only chance is
to ascend up through the tower - solving a host of puzzles on your way to
your rescue.

%if "%{?vendor}" == "chum"
Title: Dead Ascend
Type: desktop-application
DeveloperName: Black Grain Games
PackagedBy: nephros
Categories:
 - Game
Custom:
  Repo: https://github.com/larpon/DeadAscend/
  PackagingRepo: https://github.com/nephros/harbour-deadascend
PackageIcon: https://github.com/larpon/DeadAscend/raw/master/gfx/icon.svg
Screenshots:
 - %{url}/screenshots/screen3.png
 - %{url}/screenshots/screen4.png
 - %{url}/screenshots/screen5.png
Links:
  Homepage: %{url}
  Bugtracker: https://github.com/nephros/harbour-deadascend/issues
  Donation: https://openrepos.net/donate
%endif


%package data
Summary:    Resources for %{name}
Group:      Applications
Requires:   %{name}
Provides:   %{assets_pkgname} = %{assets_version}

%description data
%{summary}.

%prep
%setup -q -n %{name}-%{version}

# qak-qt5.6.patch
%patch0 -p1
# >> setup
# << setup

%build
# >> build pre
#sed -i 's/androidextras//' extensions/qak/qak.pro

%qmake5 -r \
BIN_DIR=%{_bindir} \
ASSETS_DIR=%{_datadir}/%{name} \
%nil

make assetsrcc -C App
# << build pre



# >> build post
%make_build
# << build post

%install
# >> install pre
%make_install
# << install pre

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%license LICENSE
%{_bindir}/*
%dir %{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/*/*/apps/*.png
%{_datadir}/icons/*/scalable/apps/*.svg
# >> files
# << files

%files data
%{_datadir}/%{name}/assets.rcc
# >> files data
# << files data
