# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.34.2
# 

Name:       harbour-deadascend

# >> macros
# << macros

Summary:    A horde of zombies have chased you to the old radio tower
Version:    1.1.3
Release:    0
Group:      Applications
License:    MIT
URL:        https://blackgrain.dk/games/deadascend/
Source0:    %{name}-%{version}.tar.gz
Source100:  harbour-deadascend.yaml
Source101:  harbour-deadascend-rpmlintrc
BuildRequires:  pkgconfig(sailfishapp)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Multimedia)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  qt5-qttools-linguist
BuildRequires:  qt5-qmake
BuildRequires:  sailfish-svg2png
BuildRequires:  qml-rpm-macros
BuildRequires:  desktop-file-utils

%description
A hand-drawn, open source, point'n'click-like 2D adventure game.

A horde of Zombies chased you to the old radio tower. Your only chance is
to ascend up through the tower - solving a host of puzzles on your way to
your rescue.

%if "%{?vendor}" == "chum"
Title: Dead Ascend
Type: desktop-application
DeveloperName: Black Grain Games
PackagedBy: nephros
Categories:
 - Game
Custom:
  Repo: https://github.com/larpon/DeadAscend/
  PackagingRepo: https://github.com/nephros/harbour-deadascend
PackageIcon: https://github.com/larpon/DeadAscend/raw/master/gfx/icon.svg
Screenshots:
 - https://blackgrain.dk/games/deadascend/screenshots/screen3.png
 - https://blackgrain.dk/games/deadascend/screenshots/screen4.png
 - https://blackgrain.dk/games/deadascend/screenshots/screen5.png
Links:
  Homepage: %{url}
%endif


%prep
%setup -q -a 1 -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
sed -i 's/androidextras//' extensions/qak/qak.pro

%qmake5 -r \
BIN_DIR=%{_bindir} \
ASSETS_DIR=%{_datadir}/%{name} \
%nil

make assetsrcc -C App
# << build pre



# >> build post
%make_build
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%make_install
# << install pre

# >> install post
install -d %{buildroot}%{_datadir}/applications
install -p -m 0644 %SOURCE2 %{buildroot}%{_datadir}/applications/%{name}.desktop

install -d %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/
install -p -m 0644 gfx/icon.svg %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/%{name}.svg

for size in 86 108 128 172 256 512 1024; do
install -d %{buildroot}%{_datadir}/icons/hicolor/${size}x${size}/apps/
sailfish_svg2png -z 1.0 -f rgba -s 1 1 1 1 1 1 ${size} \
%{buildroot}%{_datadir}/icons/hicolor/scalable/apps/ \
%{buildroot}%{_datadir}/icons/hicolor/${size}x${size}/apps/
done
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%license LICENSE
%{_bindir}/*
%{_datadir}/%{name}/
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/*/*/apps/%{name}.png
%{_datadir}/icons/*/*/apps/%{name}.svg
# >> files
# << files
